---
# handlers file for postgresql_server
- name: Restart postgresql
  ansible.builtin.service:
    name: "{{ pg_service_name }}"
    state: restarted

- name: Reload postgresql
  ansible.builtin.service:
    name: "{{ pg_service_name }}"
    state: reloaded

- name: Restart pgbouncer
  ansible.builtin.service:
    name: pgbouncer
    state: restarted