---
- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Reload postgresql
  ansible.builtin.service:
    name: postgresql
    state: reloaded

- name: Restart pgbouncer
  ansible.builtin.service:
    name: pgbouncer
    state: restarted