---
galaxy_info:
  author: CreativeFlow
  description: A role to install NVIDIA drivers and container toolkit for GPU-enabled K8s nodes.
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - jammy # 22.04
dependencies:
  - role: kubernetes_common