---
- name: Check if cluster is already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_admin_conf

- name: Initialize Kubernetes control plane
  ansible.builtin.command:
    cmd: "kubeadm init --pod-network-cidr={{ k8s_pod_network_cidr }} {{ kubeadm_init_extra_args }}"
  when: not k8s_admin_conf.stat.exists
  register: kubeadm_init

- name: Create .kube directory for admin user
  ansible.builtin.file:
    path: "/home/{{ ansible_admin_user }}/.kube"
    state: directory
    owner: "{{ ansible_admin_user }}"
    group: "{{ ansible_admin_user }}"
    mode: '0755'
  when: kubeadm_init.changed

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_admin_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_admin_user }}"
    group: "{{ ansible_admin_user }}"
    mode: '0644'
  when: kubeadm_init.changed

- name: Get join command for worker nodes
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  register: kubeadm_join_command
  when: kubeadm_init.changed
  changed_when: false

- name: Store join command for other hosts
  ansible.builtin.set_fact:
    k8s_join_command: "{{ kubeadm_join_command.stdout }}"
    cacheable: true
  when: kubeadm_join_command.stdout is defined

- name: Apply CNI manifest (Calico)
  community.kubernetes.k8s:
    src: "{{ cni_manifest_url }}"
    state: present
  run_once: true
  when: not k8s_admin_conf.stat.exists