---
- name: Check if node is already part of a cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join worker node to the cluster
  ansible.builtin.command:
    cmd: "{{ hostvars[groups['k8s_masters'][0]]['join_command_workers'] }} {{ kubeadm_join_extra_args }}"
  when: not kubelet_conf.stat.exists
  changed_when: true