---
# tasks file for kubernetes_master

- name: Reset Kubernetes component if it was already configured
  ansible.builtin.command: kubeadm reset -f
  when: kubeadm_reset | bool

- name: Check if cluster is already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_init_stat

- name: Initialize the Kubernetes cluster using kubeadm
  ansible.builtin.command: "kubeadm init --pod-network-cidr={{ k8s_pod_network_cidr }} --apiserver-advertise-address={{ ansible_host }} {{ kubeadm_init_extra_args }}"
  when: not k8s_init_stat.stat.exists
  register: kubeadm_init

- name: Display kubeadm init output
  ansible.builtin.debug:
    var: kubeadm_init.stdout_lines
  when: not k8s_init_stat.stat.exists

- name: Create .kube directory for the admin user
  ansible.builtin.file:
    path: "/home/{{ ansible_admin_user }}/.kube"
    state: directory
    owner: "{{ ansible_admin_user }}"
    group: "{{ ansible_admin_user }}"
    mode: '0755'

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_admin_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_admin_user }}"
    group: "{{ ansible_admin_user }}"
    mode: '0600'

- name: Get the join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command_raw
  when: not k8s_init_stat.stat.exists

- name: Store the join command
  ansible.builtin.set_fact:
    join_command: "{{ join_command_raw.stdout }}"
    cacheable: yes
  when: join_command_raw.stdout is defined

- name: Make join command available to other hosts
  ansible.builtin.lineinfile:
    path: /tmp/k8s_join_command
    line: "{{ join_command }}"
    create: yes
    mode: '0644'
  when: join_command is defined
  delegate_to: localhost
  run_once: true

- name: Apply CNI manifest (Calico)
  community.kubernetes.k8s:
    state: present
    src: "{{ k8s_cni_manifest_url }}"
    kubeconfig: /etc/kubernetes/admin.conf
  when: not k8s_init_stat.stat.exists