# Specifies external Ansible Galaxy collections and roles required by the project,
# enabling reproducible dependency installation via `ansible-galaxy install -r requirements.yml`.

collections:
  # For a wide range of utility modules (e.g., ufw, sysctl, community.crypto)
  - name: community.general
    version: ">=6.0.0"

  # For managing Docker containers and services
  - name: community.docker
    version: ">=3.0.0"

  # For interaction with Kubernetes APIs to manage resources (e.g., apply manifests)
  - name: community.kubernetes
    version: ">=2.0.0"

  # For advanced PostgreSQL management tasks (e.g., user creation, replication management)
  - name: community.postgresql
    version: ">=2.0.0"

# roles:
#  # Example of how to include a role from Ansible Galaxy
#  - name: geerlingguy.nginx
#    version: 4.1.0