name: creativeflow_flutter_app
description: The native mobile application for CreativeFlow AI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  provider: ^6.1.2 # Often used with BLoC for DI

  # Navigation
  go_router: ^14.1.0

  # Networking
  http: ^1.2.1
  
  # Local Storage
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.22
  path_provider: ^2.1.3
  path: ^1.9.0

  # Native Integrations & Utilities
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  firebase_analytics: ^11.1.0
  firebase_crashlytics: ^4.0.2
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  speech_to_text: ^6.6.2
  connectivity_plus: ^6.0.3
  
  # Dependency Injection
  get_it: ^7.7.0

  # Other utilities
  intl: ^0.19.0
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.11
  drift_dev: ^2.18.0
  
  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/l10n/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700