---
# This playbook orchestrates the setup of the entire Kubernetes cluster
# by applying roles in a specific sequence.

- name: 1. Apply common Kubernetes configuration to all nodes
  hosts: k8s_masters, k8s_workers, k8s_workers_gpu
  roles:
    - role: kubernetes_common

- name: 2. Install GPU support on designated worker nodes
  hosts: k8s_workers_gpu
  roles:
    - role: gpu_support

- name: 3. Initialize Kubernetes master nodes
  hosts: k8s_masters
  serial: 1 # Initialize masters one by one to avoid race conditions
  roles:
    - role: kubernetes_master

- name: 4. Join worker nodes to the cluster
  hosts: k8s_workers, k8s_workers_gpu
  roles:
    - role: kubernetes_worker