---
# Role to install and configure MinIO server cluster.
# This is a placeholder structure. Implementation details depend on whether
# you are setting up a single node or a distributed cluster.

- name: Create MinIO system group
  ansible.builtin.group:
    name: "{{ minio_group }}"
    state: present

- name: Create MinIO system user
  ansible.builtin.user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: yes
    shell: /sbin/nologin
    comment: "MinIO Server User"
    create_home: no

- name: Download MinIO binary
  ansible.builtin.get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
    dest: "/usr/local/bin/minio"
    mode: '0755'
    checksum: "sha256:{{ minio_checksum }}" # Get checksum from MinIO website for the version

- name: Create MinIO data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: '0750'
  loop: "{{ minio_data_dirs }}"

- name: Create MinIO config directory
  ansible.builtin.file:
    path: "{{ minio_config_dir }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: '0750'

- name: Deploy MinIO environment file
  ansible.builtin.template:
    src: minio.conf.j2
    dest: "{{ minio_config_dir }}/minio.conf"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: '0640'
  notify: Restart minio

- name: Deploy systemd service file for MinIO
  ansible.builtin.template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart minio

- name: Enable and start MinIO service
  ansible.builtin.systemd:
    name: minio
    state: started
    enabled: yes
    daemon_reload: yes