---
# tasks file for kubernetes_worker

- name: Reset Kubernetes component if it was already configured
  ansible.builtin.command: kubeadm reset -f
  when: kubeadm_reset | bool

- name: Check if node has already joined the cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- name: Retrieve the join command from the master
  ansible.builtin.slurp:
    src: /tmp/k8s_join_command
  register: join_command_b64
  delegate_to: localhost
  run_once: true

- name: Join the worker node to the cluster
  ansible.builtin.command: "{{ join_command_b64['content'] | b64decode }} {{ kubeadm_join_extra_args }}"
  when: not kubelet_conf_stat.stat.exists