---
# Handlers for the 'prometheus_exporters' role

- name: restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes

- name: restart postgres_exporter
  ansible.builtin.systemd:
    name: postgres_exporter
    state: restarted
    daemon_reload: yes