---
collections:
  # General purpose utilities and modules
  - name: community.general
    version: ">=6.0.0"

  # Modules for managing Docker containers and services
  - name: community.docker
    version: ">=3.0.0"

  # Modules for interacting with the Kubernetes API
  - name: community.kubernetes
    version: ">=2.0.0"

  # Modules for advanced PostgreSQL management
  - name: community.postgresql
    version: ">=2.0.0"

# roles:
#   # Example for an external role from Ansible Galaxy
#   # - name: geerlingguy.nginx
#   #   version: 3.2.0