---
galaxy_info:
  author: CreativeFlow AI
  description: Role to install and configure Nginx as a reverse proxy / load balancer.
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - jammy (22.04)
  galaxy_tags:
    - web
    - nginx
    - proxy
    - loadbalancer

dependencies: []