apiVersion: v1
kind: Service
metadata:
  name: gpt2-triton-service
  namespace: creativeflow-ai-serving
  labels:
    app: gpt2-triton
    runtime: triton
    creativeflow.ai/scrape-metrics: "true" # Allows the base ServiceMonitor to discover this service
spec:
  selector:
    app: gpt2-triton
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: http
  - name: grpc
    protocol: TCP
    port: 8001
    targetPort: grpc
  - name: http-metrics
    protocol: TCP
    port: 8002
    targetPort: http-metrics
  type: ClusterIP