---
- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted

- name: Restart postgres_exporter
  ansible.builtin.systemd:
    name: postgres_exporter
    state: restarted

- name: Restart rabbitmq_exporter
  ansible.builtin.systemd:
    name: rabbitmq_exporter
    state: restarted