---
# Default variables for the 'gpu_support' role

# NVIDIA driver version. Should be chosen based on hardware and CUDA version compatibility.
# 'latest' can be used, but pinning a version is safer for production.
nvidia_driver_version: "535"

# NVIDIA Container Toolkit repository URL
nvidia_container_toolkit_repo_url: "https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-libnvidia-container.list"
nvidia_container_toolkit_repo_key_url: "https://nvidia.github.io/libnvidia-container/gpgkey"

# NVIDIA GPU Operator Helm chart details
gpu_operator_helm_repo_name: "nvidia"
gpu_operator_helm_repo_url: "https://helm.ngc.nvidia.com/nvidia"
gpu_operator_chart_name: "gpu-operator"
gpu_operator_chart_version: "v23.9.1" # It's recommended to pin the chart version
gpu_operator_namespace: "gpu-operator"
gpu_operator_release_name: "gpu-operator"