apiVersion: v1
kind: ConfigMap
metadata:
  name: resnet50-tfserving-config
  namespace: creativeflow-ai-serving
data:
  models.config: |
    model_config_list: {
      config: {
        name: "resnet50",
        base_path: "/models/resnet50", # Path inside the container where model files are
        model_platform: "tensorflow",
        model_version_policy: {
          latest: {
            num_versions: 1
          }
        }
      }
      # Add other models here if this TF Serving instance should serve multiple models
      # config: {
      #   name: "another_model",
      #   base_path: "/models/another_model",
      #   model_platform: "tensorflow"
      # }
    }