apiVersion: v1
kind: Service
metadata:
  name: resnet50-tfserving-service
  namespace: creativeflow-ai-serving
  labels:
    app: resnet50-tfserving
    runtime: tensorflow-serving
    # This label allows the base ServiceMonitor to discover and scrape this service
    # if a metrics port is configured and exposed by the container.
    creativeflow.ai/scrape-metrics: "true" 
spec:
  selector:
    app: resnet50-tfserving
  ports:
  - name: grpc
    protocol: TCP
    port: 8500
    targetPort: grpc
  - name: http
    protocol: TCP
    port: 8501 # Service port for HTTP
    targetPort: http # Target port name on the pod
  # - name: metrics # Uncomment if TF Serving is configured to expose Prometheus metrics
  #   protocol: TCP
  #   port: 8502
  #   targetPort: metrics
  type: ClusterIP