---
# Placeholder vars for 'rabbitmq_server' role.
# Admin user and password should be defined in vaulted files.
# rabbitmq_admin_user: "admin"
# rabbitmq_admin_password: "{{ rabbitmq_admin_pass_from_vault }}"