---
- name: Create group for prometheus exporters
  ansible.builtin.group:
    name: "{{ prometheus_exporters_group }}"
    state: present
    system: true

- name: Create user for prometheus exporters
  ansible.builtin.user:
    name: "{{ prometheus_exporters_user }}"
    group: "{{ prometheus_exporters_group }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false

- name: Install Node Exporter
  ansible.builtin.include_tasks: node_exporter.yml
  when: "'all_servers' in group_names" # Or a more specific group

- name: Install PostgreSQL Exporter
  ansible.builtin.include_tasks: postgres_exporter.yml
  when: "'db_primary' in group_names or 'db_replicas' in group_names"

# Add other include_tasks for other exporters (e.g., rabbitmq, redis) with appropriate when conditions