---
- name: Download and unarchive PostgreSQL Exporter
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ postgres_exporter_version }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: true
    creates: "/tmp/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64/postgres_exporter"

- name: Copy PostgreSQL Exporter binary to bin directory
  ansible.builtin.copy:
    src: "/tmp/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64/postgres_exporter"
    dest: "{{ prometheus_exporters_bin_dir }}/postgres_exporter"
    remote_src: true
    mode: '0755'
    owner: "{{ prometheus_exporters_user }}"
    group: "{{ prometheus_exporters_group }}"

- name: Deploy PostgreSQL Exporter systemd service file
  ansible.builtin.template:
    src: postgres_exporter.service.j2
    dest: /etc/systemd/system/postgres_exporter.service
    mode: '0644'
  notify: restart postgres_exporter

- name: Enable and start PostgreSQL Exporter service
  ansible.builtin.systemd:
    name: postgres_exporter
    state: started
    enabled: true
    daemon_reload: true