---
- name: Add NVIDIA package repository key
  ansible.builtin.apt_key:
    url: "{{ nvidia_repo_key_url }}"
    state: present

- name: Add NVIDIA package repository
  ansible.builtin.apt_repository:
    repo: "{{ nvidia_repo_url }}"
    state: present
    update_cache: yes

- name: Install NVIDIA drivers and CUDA toolkit
  ansible.builtin.apt:
    name:
      - "cuda-drivers-{{ nvidia_driver_version }}"
      - "cuda-toolkit-{{ nvidia_cuda_version }}"
    state: present

- name: Add NVIDIA Container Toolkit repository key
  ansible.builtin.apt_key:
    url: "{{ nvidia_container_toolkit_key_url }}"
    state: present

- name: Add NVIDIA Container Toolkit repository
  ansible.builtin.apt_repository:
    repo: "{{ nvidia_container_toolkit_repo_url }}"
    state: present

- name: Install NVIDIA Container Toolkit
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    state: present
  notify: Restart containerd

- name: Configure containerd to use NVIDIA runtime
  ansible.builtin.command: nvidia-ctk runtime configure --runtime=containerd
  changed_when: true # This command is not idempotent by default
  notify: Restart containerd

- name: Deploy NVIDIA GPU Operator manifest
  community.kubernetes.k8s:
    state: present
    src: "{{ nvidia_gpu_operator_manifest_url }}"
  delegate_to: localhost
  run_once: true
  when: "'k8s_masters' in group_names and inventory_hostname == groups['k8s_masters'][0]"