---
galaxy_info:
  author: CreativeFlow AI
  description: Role to join a Kubernetes worker node to a cluster.
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - "jammy" # 22.04
  galaxy_tags:
    - kubernetes
    - worker
    - node

dependencies:
  - role: kubernetes_common