---
galaxy_info:
  author: CreativeFlow AI
  description: Role to install and configure PostgreSQL with replication and PgBouncer.
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - jammy (22.04)
  galaxy_tags:
    - database
    - postgres
    - postgresql
    - replication

dependencies: []