---
galaxy_info:
  author: CreativeFlow
  description: Role to install and configure PostgreSQL servers with replication.
  license: proprietary
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - database
    - postgres
    - postgresql
    - replication

dependencies: []