---
# handlers file for gpu_support
- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Reboot after driver install
  ansible.builtin.reboot:
    msg: "Rebooting to finalize NVIDIA driver installation."
    reboot_timeout: 300