---
- name: Restart postgresql
  ansible.builtin.service:
    name: "{{ pg_service_name }}"
    state: restarted

- name: Restart pgbouncer
  ansible.builtin.service:
    name: pgbouncer
    state: restarted