---
# tasks file for kubernetes_common

- name: Ensure legacy iptables is used
  ansible.builtin.command: update-alternatives --set iptables /usr/sbin/iptables-legacy
  changed_when: true

- name: Load required kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Persist required kernel modules
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf
    mode: '0644'

- name: Configure required sysctl settings for Kubernetes networking
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    state: present
    reload: yes
  loop:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0
  changed_when: true

- name: Remove swap from fstab to disable permanently
  ansible.posix.mount:
    name: swap
    fstype: swap
    state: absent

- name: Add Kubernetes apt repository key
  ansible.builtin.get_url:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    mode: '0644'

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes

- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: yes

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate default containerd config
  ansible.builtin.command: containerd config default
  register: containerd_config_default
  changed_when: false

- name: Configure containerd to use systemd cgroup driver
  ansible.builtin.copy:
    content: "{{ containerd_config_default.stdout | regex_replace('SystemdCgroup = false', 'SystemdCgroup = true') }}"
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: Restart containerd

- name: Ensure containerd service is started and enabled
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: yes

- name: Install kubelet, kubeadm, and kubectl
  ansible.builtin.apt:
    name:
      - "kubelet={{ k8s_version }}-00"
      - "kubeadm={{ k8s_version }}-00"
      - "kubectl={{ k8s_version }}-00"
    state: present
    allow_downgrade: yes
  notify: Restart kubelet

- name: Hold kubelet, kubeadm, and kubectl versions
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl